# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:14.2-alpine
    container_name: "my_postgres"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} # "t6PvUXcCr2DZ5DYh"
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  # redis:
  #   image: redis:6.2.7-alpine
  #   container_name: "my_redis"
  #   restart: always
  #   ports:
  #     - '6379:6379'
  #   command: redis-server --save 60 1 --loglevel warning
  #   volumes: 
  #     - ./redis:/data

  adminer:
    image: adminer
    container_name: "adminer"
    restart: always
    ports:
      - 8080:8080

  mongo:
    image: mongo
    restart: always
    container_name: "mongo"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./mongodb:/data/db
    ports:
      - 27017:27017

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   container_name: "mongo_admin"
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
  #     ME_CONFIG_MONGODB_URL: mongodb://root:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/

volumes:
  db:


