---
- name : Déploiement sur le serveur
  hosts: all
  remote_user: "{{ user }}"
  tasks:
    - include_vars:
        file: vars.yml
    - name: DEPLOY |  salts & keys
      set_fact:
        session_secret: "{{ lookup('password', '/dev/null length=32 chars=ascii_letters,digits') }}"
        api_salt: "{{ lookup('password', '/dev/null length=32 chars=ascii_letters,digits') }}"
        token_salt: "{{ lookup('password', '/dev/null length=16 chars=ascii_letters,digits') }}"
        cacheable: yes        
    - include_role:
        name: ansistrano.deploy
    