---
# tasks file for postgres
- name: POSTGRES | server
  apt:
    name:
      - postgresql
    state: present
- name: POSTGRES | Install dependancies
  apt:
    name:
      - python3-psycopg2
    state: present
- name: "POSTGRES | Create {{ db_user }}"
  community.postgresql.postgresql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    state: present
  become: yes
  become_user: postgres
  environment:
    PGOPTIONS: "-c password_encryption=scram-sha-256"
- name: "POSTGRES | Create a new database '{{ db_name }}' for user '{{ db_user }}' "
  community.postgresql.postgresql_db:
    name: "{{ db_name }}"
    owner: "{{ db_user }}"
    encoding: UTF-8
    state: present
  become: yes
  become_user: postgres
- name: "GRANT ALL PRIVILEGES ON SCHEMA public TO {{ db_user }}"
  community.postgresql.postgresql_privs:
    type: database
    database: "{{ db_name }}"
    roles: "{{ db_user }}"
    grant_option: no
    privs: ALL
  become: yes
  become_user: postgres
  notify: restart postgres
